<Route path="/css" key="/css" exact>{<Suspense fallback={<div>loading</div>}><CSS/></Suspense>}</Route>
<Route path="/css/flex" key="/css/flex" exact>{<Suspense fallback={<div>loading</div>}><CSSFLEX/></Suspense>}</Route>
<Route path="/javascript" key="/javascript" exact>{<Suspense fallback={<div>loading</div>}><JAVASCRIPT/></Suspense>}</Route>
<Route path="/javascript/closure" key="/javascript/closure" exact>{<Suspense fallback={<div>loading</div>}><JAVASCRIPTCLOSURE/></Suspense>}</Route>
<Route path="/javascript/debounce" key="/javascript/debounce" exact>{<Suspense fallback={<div>loading</div>}><JAVASCRIPTDEBOUNCE/></Suspense>}</Route>
<Route path="/javascript/deepClone" key="/javascript/deepClone" exact>{<Suspense fallback={<div>loading</div>}><JAVASCRIPTDEEPCLONE/></Suspense>}</Route>
<Route path="/javascript/es6" key="/javascript/es6" exact>{<Suspense fallback={<div>loading</div>}><JAVASCRIPTES/></Suspense>}</Route>
<Route path="/javascript/promise" key="/javascript/promise" exact>{<Suspense fallback={<div>loading</div>}><JAVASCRIPTPROMISE/></Suspense>}</Route>
<Route path="/javascript/prototype" key="/javascript/prototype" exact>{<Suspense fallback={<div>loading</div>}><JAVASCRIPTPROTOTYPE/></Suspense>}</Route>
<Route path="/projects" key="/projects" exact>{<Suspense fallback={<div>loading</div>}><PROJECTS/></Suspense>}</Route>
<Route path="/projects/linktime" key="/projects/linktime" exact>{<Suspense fallback={<div>loading</div>}><PROJECTSLINKTIME/></Suspense>}</Route>
<Route path="/projects/okr" key="/projects/okr" exact>{<Suspense fallback={<div>loading</div>}><PROJECTSOKR/></Suspense>}</Route>
<Route path="/projects/torture" key="/projects/torture" exact>{<Suspense fallback={<div>loading</div>}><PROJECTSTORTURE/></Suspense>}</Route>
<Route path="/projects/ui-framework" key="/projects/ui-framework" exact>{<Suspense fallback={<div>loading</div>}><PROJECTSUIFRAMEWORK/></Suspense>}</Route>
<Route path="/react" key="/react" exact>{<Suspense fallback={<div>loading</div>}><REACT/></Suspense>}</Route>
<Route path="/react/diff" key="/react/diff" exact>{<Suspense fallback={<div>loading</div>}><REACTDIFF/></Suspense>}</Route>
<Route path="/react/fiber" key="/react/fiber" exact>{<Suspense fallback={<div>loading</div>}><REACTFIBER/></Suspense>}</Route>
<Route path="/react/hooks" key="/react/hooks" exact>{<Suspense fallback={<div>loading</div>}><REACTHOOKS/></Suspense>}</Route>
<Route path="/react/hooks/useEffect" key="/react/hooks/useEffect" exact>{<Suspense fallback={<div>loading</div>}><REACTHOOKSUSEEFFECT/></Suspense>}</Route>
<Route path="/react/hooks/useState" key="/react/hooks/useState" exact>{<Suspense fallback={<div>loading</div>}><REACTHOOKSUSESTATE/></Suspense>}</Route>
<Route path="/react/performance" key="/react/performance" exact>{<Suspense fallback={<div>loading</div>}><REACTPERFORMANCE/></Suspense>}</Route>
<Route path="/react/redux" key="/react/redux" exact>{<Suspense fallback={<div>loading</div>}><REACTREDUX/></Suspense>}</Route>
<Route path="/vue" key="/vue" exact>{<Suspense fallback={<div>loading</div>}><VUE/></Suspense>}</Route>
<Route path="/vue/diff" key="/vue/diff" exact>{<Suspense fallback={<div>loading</div>}><VUEDIFF/></Suspense>}</Route>
<Route path="/vue/directives" key="/vue/directives" exact>{<Suspense fallback={<div>loading</div>}><VUEDIRECTIVES/></Suspense>}</Route>
<Route path="/vue/key" key="/vue/key" exact>{<Suspense fallback={<div>loading</div>}><VUEKEY/></Suspense>}</Route>
<Route path="/vue/nextTick" key="/vue/nextTick" exact>{<Suspense fallback={<div>loading</div>}><VUENEXTTICK/></Suspense>}</Route>
<Route path="/vue/vuex" key="/vue/vuex" exact>{<Suspense fallback={<div>loading</div>}><VUEVUEX/></Suspense>}</Route>
<Route path="/vue/watch" key="/vue/watch" exact>{<Suspense fallback={<div>loading</div>}><VUEWATCH/></Suspense>}</Route>
<Route path="/webBrowser" key="/webBrowser" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSER/></Suspense>}</Route>
<Route path="/webBrowser/cookie" key="/webBrowser/cookie" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERCOOKIE/></Suspense>}</Route>
<Route path="/webBrowser/crossPage" key="/webBrowser/crossPage" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERCROSSPAGE/></Suspense>}</Route>
<Route path="/webBrowser/crossPage/Broadcast Channe" key="/webBrowser/crossPage/Broadcast Channe" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERCROSSPAGEBROADCASTCHANNE/></Suspense>}</Route>
<Route path="/webBrowser/crossPage/IndexedDB" key="/webBrowser/crossPage/IndexedDB" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERCROSSPAGEINDEXEDDB/></Suspense>}</Route>
<Route path="/webBrowser/crossPage/LocalStorage" key="/webBrowser/crossPage/LocalStorage" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERCROSSPAGELOCALSTORAGE/></Suspense>}</Route>
<Route path="/webBrowser/crossPage/Service Worker" key="/webBrowser/crossPage/Service Worker" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERCROSSPAGESERVICEWORKER/></Suspense>}</Route>
<Route path="/webBrowser/crossPage/Shared Worker" key="/webBrowser/crossPage/Shared Worker" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERCROSSPAGESHAREDWORKER/></Suspense>}</Route>
<Route path="/webBrowser/crossPage/window open opener" key="/webBrowser/crossPage/window open opener" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERCROSSPAGEWINDOWOPENOPENER/></Suspense>}</Route>
<Route path="/webBrowser/garbageCycle" key="/webBrowser/garbageCycle" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERGARBAGECYCLE/></Suspense>}</Route>
<Route path="/webBrowser/garbageCycle/memoryLeak" key="/webBrowser/garbageCycle/memoryLeak" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERGARBAGECYCLEMEMORYLEAK/></Suspense>}</Route>
<Route path="/webBrowser/performance" key="/webBrowser/performance" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERPERFORMANCE/></Suspense>}</Route>
<Route path="/webBrowser/pwa" key="/webBrowser/pwa" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERPWA/></Suspense>}</Route>
<Route path="/webBrowser/safety" key="/webBrowser/safety" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERSAFETY/></Suspense>}</Route>
<Route path="/webBrowser/safety/csrf" key="/webBrowser/safety/csrf" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERSAFETYCSRF/></Suspense>}</Route>
<Route path="/webBrowser/safety/xss" key="/webBrowser/safety/xss" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERSAFETYXSS/></Suspense>}</Route>
<Route path="/webBrowser/sso" key="/webBrowser/sso" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERSSO/></Suspense>}</Route>
<Route path="/webBrowser/ssr-hydrate" key="/webBrowser/ssr-hydrate" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERSSRHYDRATE/></Suspense>}</Route>
<Route path="/webBrowser/tcp-tls" key="/webBrowser/tcp-tls" exact>{<Suspense fallback={<div>loading</div>}><WEBBROWSERTCPTLS/></Suspense>}</Route>
<Route path="/webpack" key="/webpack" exact>{<Suspense fallback={<div>loading</div>}><WEBPACK/></Suspense>}</Route>
<Route path="/webpack/micro-front" key="/webpack/micro-front" exact>{<Suspense fallback={<div>loading</div>}><WEBPACKMICROFRONT/></Suspense>}</Route>
<Route path="/webpack/perfomance" key="/webpack/perfomance" exact>{<Suspense fallback={<div>loading</div>}><WEBPACKPERFOMANCE/></Suspense>}</Route>
<Route path="/webpack/progress" key="/webpack/progress" exact>{<Suspense fallback={<div>loading</div>}><WEBPACKPROGRESS/></Suspense>}</Route>